version: "3.8"
services:
  backend:
    image: "johnofagbe/springboot-react-fullstack:8.3.2023.1.58.45"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev